
public class FaturaOdemeEkrani extends javax.swing.JFrame {

    /**
     * Creates new form FaturaOdemeEkrani
     */
    String tcNo=null;
    String sifre =null;
    String ad =null;
    String soyad=null;
    String hesapno =null;
    public FaturaOdemeEkrani() {
        initComponents();
    }
   
public FaturaOdemeEkrani(String []x) {
        initComponents();
        tcNo=x[0];
        sifre=x[1];
        ad=x[2];
        soyad=x[3];
        hesapno=x[4];
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        elektrik = new javax.swing.JButton();
        dogalgaz = new javax.swing.JButton();
        su = new javax.swing.JButton();
        telefon = new javax.swing.JButton();
        geri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("LÜTFEN BİR İŞLEM ŞEÇİNİZ: ");

        elektrik.setBackground(new java.awt.Color(0, 0, 0));
        elektrik.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        elektrik.setForeground(new java.awt.Color(255, 255, 255));
        elektrik.setText("ELEKTRİK FATURASI ÖDEME");
        elektrik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elektrikActionPerformed(evt);
            }
        });

        dogalgaz.setBackground(new java.awt.Color(0, 0, 0));
        dogalgaz.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        dogalgaz.setForeground(new java.awt.Color(255, 255, 255));
        dogalgaz.setText("DOĞALGAZ FATURASI ÖDEME");
        dogalgaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dogalgazActionPerformed(evt);
            }
        });

        su.setBackground(new java.awt.Color(0, 0, 0));
        su.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        su.setForeground(new java.awt.Color(255, 255, 255));
        su.setText("SU FATURASI ÖDEME");
        su.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suActionPerformed(evt);
            }
        });

        telefon.setBackground(new java.awt.Color(0, 0, 0));
        telefon.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        telefon.setForeground(new java.awt.Color(255, 255, 255));
        telefon.setText("TELEFON FATURASI ÖDEME");
        telefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonActionPerformed(evt);
            }
        });

        geri.setBackground(new java.awt.Color(0, 0, 0));
        geri.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        geri.setForeground(new java.awt.Color(255, 255, 255));
        geri.setText("GERİ");
        geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dogalgaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(elektrik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(su, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(telefon, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(geri, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(250, 250, 250))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elektrik, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(su, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dogalgaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telefon, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(geri, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriActionPerformed
    setVisible(false);
    }//GEN-LAST:event_geriActionPerformed

    private void elektrikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elektrikActionPerformed
       MusteriHesabi musteri =new MusteriHesabi();
       musteri.tcNo=Integer.parseInt(tcNo);
       musteri.hesapNo=Integer.parseInt(hesapno);
       Fatura elektrik=new Fatura();
       elektrik.elektrik(musteri.hesapNo, musteri.tcNo);
    }//GEN-LAST:event_elektrikActionPerformed

    private void suActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suActionPerformed
MusteriHesabi musteri =new MusteriHesabi();
       musteri.tcNo=Integer.parseInt(tcNo);
       musteri.hesapNo=Integer.parseInt(hesapno);
       Fatura su=new Fatura();
       su.su(musteri.hesapNo, musteri.tcNo);        // TODO add your handling code here:
    }//GEN-LAST:event_suActionPerformed

    private void dogalgazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dogalgazActionPerformed
MusteriHesabi musteri =new MusteriHesabi();
       musteri.tcNo=Integer.parseInt(tcNo);
       musteri.hesapNo=Integer.parseInt(hesapno);
       Fatura gaz=new Fatura();
      gaz.dogalgaz(musteri.hesapNo, musteri.tcNo);        // TODO add your handling code here:
    }//GEN-LAST:event_dogalgazActionPerformed

    private void telefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonActionPerformed
MusteriHesabi musteri =new MusteriHesabi();
       musteri.tcNo=Integer.parseInt(tcNo);
       musteri.hesapNo=Integer.parseInt(hesapno);
       Fatura telefon=new Fatura();
       telefon.telefon(musteri.hesapNo, musteri.tcNo);        // TODO add your handling code here:
    }//GEN-LAST:event_telefonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FaturaOdemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FaturaOdemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FaturaOdemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FaturaOdemeEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               FaturaOdemeEkrani f= new FaturaOdemeEkrani();
                       f.setVisible(true);
            }
            public void run2() {
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dogalgaz;
    private javax.swing.JButton elektrik;
    private javax.swing.JButton geri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton su;
    private javax.swing.JButton telefon;
    // End of variables declaration//GEN-END:variables
}
