
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ListIterator;
import java.util.Vector;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Legion
 */
public class OnayEkrani2 extends javax.swing.JFrame {

    /**
     * Creates new form OnayEkrani
     */
    public OnayEkrani2() {
        initComponents();
      try{   
           FileReader fr =new FileReader("kredikartbasvurusu.txt");
            BufferedReader buf=new BufferedReader(fr);
           
            String satir;
            String satir2=" ";
            int i=0;
            while ((satir=buf.readLine())!=null){
               String [] words=satir.split(" ");
               if(i==0){
                  satir2+=" "+satir+" "; 
                  i++;
                
               }else {
                   satir2+=i+") "+satir+" ";    
                    i++;
               }
              
              
            } 
            ekran2.setText(satir2);
           fr.close();
           buf.close();       
       }catch(FileNotFoundException f)
        {System.out.println("dosya yok");}
        catch(IOException ioex)
        {System.out.println("başka bir hata oldu"); }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        onay = new javax.swing.JButton();
        reddet = new javax.swing.JButton();
        gir = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ekran2 = new javax.swing.JTextArea();
        cikis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        onay.setBackground(new java.awt.Color(0, 0, 0));
        onay.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        onay.setForeground(new java.awt.Color(255, 255, 255));
        onay.setText("ONAY");
        onay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onayActionPerformed(evt);
            }
        });

        reddet.setBackground(new java.awt.Color(0, 0, 0));
        reddet.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        reddet.setForeground(new java.awt.Color(255, 255, 255));
        reddet.setText("RED");
        reddet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reddetActionPerformed(evt);
            }
        });

        gir.setBackground(new java.awt.Color(0, 0, 0));
        gir.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        gir.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bir Sayı Girin:");

        ekran2.setEditable(false);
        ekran2.setColumns(20);
        ekran2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ekran2.setRows(5);
        jScrollPane2.setViewportView(ekran2);

        cikis.setBackground(new java.awt.Color(0, 0, 0));
        cikis.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cikis.setForeground(new java.awt.Color(255, 255, 255));
        cikis.setText("ÇIKIŞ");
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(onay, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(reddet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(cikis)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reddet, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onay, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cikis)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reddetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reddetActionPerformed
        
        Vector<String> v = new Vector<String>();
        try{   
           FileReader fr =new FileReader("kredikartbasvurusu.txt");
            BufferedReader buf=new BufferedReader(fr);
            String satir;
            int sayac=0;
            while ((satir=buf.readLine())!=null){
                String []words=satir.split(" ");
                if(sayac!=Integer.parseInt(gir.getText())){
                   for(int i=0;i<words.length;i++){
                    v.add(words[i]);                  
                }             
                } 
                sayac++;
            } 
           fr.close();
           buf.close();       
       }catch(FileNotFoundException f)
        {System.out.println("dosya yok");}
        catch(IOException ioex)
        {System.out.println("başka bir hata oldu"); }
    
    File f=new File("kredikartbasvurusu.txt");
    f.delete();   
   try(BufferedWriter br = new BufferedWriter(new FileWriter(f,true))){
    ListIterator iter = v.listIterator();
                int i=1;
                while (iter.hasNext()) {              
                    br.write((String)iter.next());
                    if(i%2==0&&i!=v.size()){
                        br.newLine();
                    }
                    else br.write(" ");
                    i++;
                }
                br.close();
} catch (IOException e) {
    System.out.println("Unable to read file " +f.toString());
} 
JOptionPane.showMessageDialog(null, "Kredi Kart Talebi Reddedildi.");
   setVisible(false);   
    }//GEN-LAST:event_reddetActionPerformed

    private void onayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onayActionPerformed
   Personel personel=new Personel();
   PersonelIslemleri yeni =new PersonelIslemleri();
   String s=gir.getText();
   yeni.krediKartiOnayiVer(s);
   JOptionPane.showMessageDialog(null, "Kredi Kartı Onayı Verilmiştir.");
   setVisible(false);   
    }//GEN-LAST:event_onayActionPerformed

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed
setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_cikisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OnayEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OnayEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OnayEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OnayEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OnayEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cikis;
    private javax.swing.JTextArea ekran2;
    private javax.swing.JTextField gir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton onay;
    private javax.swing.JButton reddet;
    // End of variables declaration//GEN-END:variables
}
